import React, { useState } from 'react';
import { StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import FeatureScreen, { SectionTitle } from '../../components/common/FeatureScreen';
import AppButton from '../../components/common/AppButton';
import AppCard from '../../components/common/AppCard';
import SpeechButton from '../../components/communication/SpeechButton';
import { useTheme } from '../../theme';
const CATEGORIES = { Needs: [['Water','Drink'],['Food','I am hungry'],['Bathroom','I need the bathroom'],['Help','I need help']], Feelings: [['Happy','I feel happy'],['Sad','I feel sad'],['Worried','I feel worried'],['Calm','I feel calm']], People: [['Family','my family'],['Friend','my friend'],['Teacher','my teacher']], Activities: [['Rest','I want to rest'],['Learn','I want to learn'],['Go','I want to go']], Emergency: [['Help now','I need help now'],['Call caregiver','Please call my caregiver']] };
export default function AACScreen({ navigation }) { const { theme } = useTheme(); const [category,setCategory]=useState('Needs'); const [parts,setParts]=useState([]); const sentence=parts.join(' '); return <FeatureScreen navigation={navigation} title="AAC communication" subtitle="Tap large buttons to build a message"><SectionTitle>Choose a category</SectionTitle><View style={styles.wrap}>{Object.keys(CATEGORIES).map(x=><TouchableOpacity accessibilityRole="button" key={x} onPress={()=>setCategory(x)} style={[styles.category,{backgroundColor:category===x?theme.colors.primary:theme.colors.surface,borderColor:theme.colors.border}]}><Text style={{color:category===x?'#fff':theme.colors.text}}>{x}</Text></TouchableOpacity>)}</View><SectionTitle>Your message</SectionTitle><AppCard><Text accessibilityLiveRegion="polite" style={[styles.sentence,{color:theme.colors.text}]}>{sentence || 'Your selected words will appear here.'}</Text><View style={styles.actions}><AppButton title="Clear" variant="outline" fullWidth={false} disabled={!sentence} onPress={()=>setParts([])} /><SpeechButton text={sentence} size="large" /></View></AppCard><SectionTitle>{category}</SectionTitle><View style={styles.grid}>{CATEGORIES[category].map(([label,text])=><TouchableOpacity accessibilityRole="button" accessibilityHint={`Add ${text} to message`} key={label} onPress={()=>setParts(p=>[...p,text])} style={[styles.tile,{backgroundColor:theme.colors.surface,borderColor:theme.colors.primary,borderRadius:theme.borderRadius.lg}]}><Text style={styles.symbol}>{label.slice(0,1)}</Text><Text style={[styles.tileText,{color:theme.colors.text}]}>{label}</Text></TouchableOpacity>)}</View></FeatureScreen>; }
const styles=StyleSheet.create({wrap:{flexDirection:'row',flexWrap:'wrap',gap:8},category:{minHeight:48,paddingHorizontal:14,borderWidth:1,justifyContent:'center',borderRadius:12},sentence:{fontSize:20,lineHeight:28,minHeight:56},actions:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:12},grid:{flexDirection:'row',flexWrap:'wrap',gap:12},tile:{width:'47%',minHeight:112,borderWidth:2,alignItems:'center',justifyContent:'center',padding:12},symbol:{fontSize:30,fontWeight:'bold'},tileText:{fontSize:17,fontWeight:'600',marginTop:8,textAlign:'center'}});
